
#define IDH_TOPIC_NIJANUS_GLANCE_2_2_1                                               1
#define IDH_TOPIC_OPTICHESKAYA_ILLYUZIYA_KAK_FENOMEN_ZRITELNOGO_VOSPRIYATIYA         36
#define IDH_TOPIC_IZBRANNYE_OPTIKO_GEOMETRICHESKIE_ILLYUZII                          37
#define IDH_TOPIC_ILLYUZIYA_PONTSO                                                   38
#define IDH_TOPIC_KOMNATA_EHJMSA                                                     39
#define IDH_TOPIC_ANAMORFOZY                                                         40
#define IDH_TOPIC_SFERA_NAUCHNYKH_ISSLEDOVANIJ                                       41
#define IDH_TOPIC_APOKRIFICHESKAYA_KOMNATA                                           42
#define IDH_TOPIC_POSTANOVKA_ZADACHI_ISSLEDOVANIYA                                   43
#define IDH_TOPIC_MODEL_TEKHNICHESKOGO_ZRENIYA                                       24
#define IDH_TOPIC_OSNOVNYE_POLOZHENIYA_BMP_PODKHODA                                  25
#define IDH_TOPIC_POLOZHENIYA_GIPOTEZY_O_RASPREDELENII_LOR_OBLASTEJ                  26
#define IDH_TOPIC_EHKSPERIMENTALNAYA_SISTEMA                                         27
#define IDH_TOPIC_POVERKHNOSTI                                                       28
#define IDH_TOPIC_ALGORITM_AVTOZAPOLNENIYA_KOORDINAT_TOCHEK_POVERKHNOSTEJ            29
#define IDH_TOPIC_PREDSTAVLENIE_VKHODNYKH_I_VYKHODNYKH_POVERKHNOSTEJ                 30
#define IDH_TOPIC_OSI_KOORDINAT                                                      31
#define IDH_TOPIC_TOCHKI_ISKHODNOGO_I_SMESHCHYENNOGO_FOKUSA                          32
#define IDH_TOPIC_FOKUSNYE_EHLLIPSOIDY                                               33
#define IDH_TOPIC_ZADACHI_POSTROENIYA                                                34
#define IDH_TOPIC_INTERFEJS_POLZOVATELYA                                             2
#define IDH_TOPIC_TSVETOVAYA_DIFFERENTSIATSIYA_OBEKTOV_EHKSPERIMENTALNOJ_SISTEMY     3
#define IDH_TOPIC_OTOBRAZHENIE_OBEKTOV_MODELI_BMP                                    4
#define IDH_TOPIC_EHLEMENTY_UPRAVLENIYA__KONTROLIRUYUSHCHIE_OTOBRAZHENIE_OBEKTOV_BMP 6
#define IDH_TOPIC_EHLEMENTY_KONTEJNERY_V_INTERFEJSE_MODELI_BMP                       7
#define IDH_TOPIC_GLAVNAYA_FORMA                                                     9
#define IDH_TOPIC_PANEL_DETALNYKH_NASTROEK                                           10
#define IDH_TOPIC_STRANITSA_PANELI_DETALNYKH_NASTROEK__ZRITELNYJ_PREDEL_             11
#define IDH_TOPIC_STRANITSA_PANELI_DETALNYKH_NASTROEK__ISKHODNYJ_FOKUS_              12
#define IDH_TOPIC_STRANITSA_PANELI_DETALNYKH_NASTROEK__SMESHCHYENNYJ_FOKUS_          13
#define IDH_TOPIC_STRANITSA_PANELI_DETALNYKH_NASTROEK__NAPRAVLENIE_FOKUSA_           14
#define IDH_TOPIC_PANEL_INSTRUMENTOV_1                                               15
#define IDH_TOPIC_MENYU                                                              16
#define IDH_TOPIC_PANEL_PROTOKOLA                                                    17
#define IDH_TOPIC_PANEL_STATUSA                                                      18
#define IDH_TOPIC_PANEL_VYVODA_GRAFIKI_MODELI_BMP                                    19
#define IDH_TOPIC_FORMA_KOORDINAT_TOCHEK_POVERKHNOSTEJ                               20
#define IDH_TOPIC_PANEL_INSTRUMENTOV_2                                               21
#define IDH_TOPIC_OBLAST_UPRAVLENIYA_TABLITSAMI_POVERKHNOSTEJ                        22
#define IDH_TOPIC_PANELI_DANNYKH_TOCHEK_POVERKHNOSTEJ                                23